import{a as h,S as b,i as L}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const w="44388505-390a672441da303f6d08bc48a";async function d(t,s){const o="https://pixabay.com/api/",a={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:s},e=await h.get(o,{params:a});return{hits:e.data.hits,totalHits:e.data.totalHits}}const E="/goit-js-hw-12/assets/alert-icon-8e3df674.svg";let v=new b(".gallery a",{overlayOpacity:.9,captionDelay:250,captionsData:"alt"});const f=document.querySelector(".gallery"),g=document.querySelector(".loader");document.querySelector(".load-more");function y(){g.style.display="block"}function c(){g.style.display="none"}function q(t){return`<a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${t.likes}</p>
        <p><b>Views:</b> ${t.views}</p>
        <p><b>Comments:</b> ${t.comments}</p>
        <p><b>Downloads:</b> ${t.downloads}</p>
      </div>
    </a>`}function O(t){return t.map(q).join("")}function p(t,s){const o=O(t);s?f.innerHTML=o:f.innerHTML+=o,v.refresh()}function i(t){L.error({message:t,messageSize:"16",messageColor:"#fff",backgroundColor:"#ef4040",position:"topLeft",close:!0,closeOnEscape:!0,closeOnClick:!0,progressBar:!0,progressBarColor:"#ffbebe",iconUrl:E,iconColor:"#fff"})}let l=1,u="",m=0;document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".search-form"),s=document.querySelector(".gallery"),o=document.querySelector(".load-more");function a(){const r=s.children[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}t.addEventListener("submit",async e=>{e.preventDefault();const r=e.target.query.value.trim();if(!r){i("Please enter a search term.");return}y(),u=r,l=1,s.innerHTML="";try{const n=await d(u,l);c(),m=n.totalHits,n.hits.length===0?(i("Sorry, there are no images matching your search query. Please try again!"),o.style.display="none"):(p(n.hits,!0),o.style.display="block")}catch(n){c(),i("An error occurred while fetching images."),console.error("Error fetching images:",n),o.style.display="none"}t.reset()}),o.addEventListener("click",async()=>{l+=1,y();try{const e=await d(u,l);c(),p(e.hits,!1),a(),l*15>=m&&(i("We're sorry, but you've reached the end of search results."),o.style.display="none")}catch(e){c(),i("An error occurred while fetching images."),console.error("Error fetching images:",e),o.style.display="none"}})});
//# sourceMappingURL=commonHelpers.js.map
